name: Gradle Publish

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Check-out
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.checkout_ref }}
          fetch-depth: 0

      - name: Setup Azul Zulu JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          java-package: 'jdk'
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          add-job-summary: 'never'
          cache-overwrite-existing: true
          gradle-version: "9.0.0"

      - name: Build and publish with Gradle
        run: ./gradlew publishPlugins --no-daemon --stacktrace
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
